image: rg.fr-par.scw.cloud/dg-builder-registry/project-builder:php8.3-node20-latest
options:
  docker: true

pipelines:
  branches:
    develop:
      - step:
          name: "Install & Test"
          caches:
            - composer
          script:
            - composer install
            - vendor/bin/phpunit