<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBoU2K3\DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBoU2K3/DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBoU2K3.legacy');

    return;
}

if (!\class_exists(DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBoU2K3\DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer::class, DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer::class, false);
}

return new \ContainerXBoU2K3\DigitalGarden_GotenbergBundle_Tests_KernelDevDebugContainer([
    'container.build_hash' => 'XBoU2K3',
    'container.build_id' => '0aa2220b',
    'container.build_time' => 1745315954,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBoU2K3');
